### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by capoxix** [capoxix/SportsWithStrangers#2]
- [x] Backend: DB, model, controller, views
  - [x] Redux Loop: ajax, actions, reducers
  - [x] Presentational Components
  - [ ] Adequate styling
  - [ ] Smooth, bug-free navigation
  - [ ] Adequate and appropriate seeds to demonstrate the feature

**Comment by eshoule** [comment]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in


## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)

### Comments
* Good job! I will close the issue when you address the unchecked boxes.
* Add more styling to make your site look more like actual website and complete the splash page styling as part of this MVP.

**Comment by eshoule** [comment]
Awesome! It's looking good - I'd like to see more styling with respect to changing the font, font sizes, etc. to reflect the actual page more, but I will close this issue.
