### ISSUE TITLE
PA Review: Host Events CRUD

### ISSUE THREAD

**Issue by capoxix** [capoxix/SportsWithStrangers#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, action, reducers
- [x] Presentational components
- [x] Logged in users can create hosted events
- [x] Logged in users can update hosted events
- [x] Logged in users can read hosted events
- [x] Logged in users can delete hosted events
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by eshoule** [comment]
Awesome job! Still need to fix some CSS - font style, making sure photos are not stretched out/get quality photos.
