### ISSUE TITLE
PA Review: Join events

### ISSUE THREAD

**Issue by capoxix** [capoxix/SportsWithStrangers#5]
- [x] Logged in users can join events in their city
- [x] Logged in users can join events waitlist
- [ ] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by eshoule** [comment]
Looks great! Work on some styling so the photos don't look stretched out and the text style matches the actual website. Maybe you should have a banner photo like the actual website has?
